name: CreeperControl
main: com.codisimus.plugins.creepercontrol.CreeperControl
version: 0.1.0
author: Codisimus
website: www.codisimus.com
description: Prevents Creepers from doing land damage
startup: postworld